apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-

resources:
- ../../base

replicas:
- name: echo-ip
  count: 3

labels:
- pairs:
    env: prod
  includeSelectors: true

patches:
- target:
    kind: Service
    name: echo-ip
  patch: |
    - op: replace
      path: /spec/type
      value: LoadBalancer
