apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # LoadBalancer: 외부에서 접속할 수 있는 공인 IP를 받습니다(브라우저 접속점).
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
