apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName 생략 시 기본 StorageClass 사용
  # - 바닐라 K8s: managed-nfs-storage
  # - GKE: standard-rwo
