{
 "title": "쿠버네티스 클러스터 모니터링",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "파드 메트릭", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "파드 별 5분간 CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "파드 별 메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", pod!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "파드 별 내부의  컨테이너 프로세스 개수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count(container_processes{namespace=~\"$namespace\", pod!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "노드 메트릭", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "노드 별 CPU 코어 개수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드 별 5분간 CPU 사용률",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (node) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "노드 별 메모리 사용률",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "클러스터 메트릭", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "쿠버네티스 노드 정보",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 19 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "네임스페이스 별 파드 개수",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "targets": [
    {
     "expr": "count(kube_pod_info) by (namespace) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}